###############################################################################
# IPv4
###############################################################################

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0

# Don't send ICMP redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Ignore source routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Log suspicious packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Reverse path filtering
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2

# Ignore bogus ICMP responses
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Ignore broadcast ICMP requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

###############################################################################
# IPv6
###############################################################################
# Disable IPv6 on all interfaces
net.ipv6.conf.all.disable_ipv6 = 1

###############################################################################
# TCP
###############################################################################

# Enable SYN cookies
net.ipv4.tcp_syncookies = 1

# RFC 1337 protection
net.ipv4.tcp_rfc1337 = 1

###############################################################################
# Kernel
###############################################################################

# Restrict BPF to privileged users
kernel.unprivileged_bpf_disabled = 1
